services:
  - type: web
    name: pdf-service
    runtime: python
    pythonVersion: "3.9.16"
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: gunicorn app:app